const net = require('net');
const fs = require('fs');
const path = require('path');

// Check if a port is available
function isPortAvailable(port) {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.listen(port, () => {
      server.once('close', () => resolve(true));
      server.close();
    });
    server.on('error', () => resolve(false));
  });
}

// Find the first available port in a range
async function findAvailablePort(startPort = 5000, maxPort = 5020) {
  console.log(`🔍 Scanning for available backend port (${startPort}-${maxPort})...`);
  
  for (let port = startPort; port <= maxPort; port++) {
    const available = await isPortAvailable(port);
    if (available) {
      console.log(`✅ Found available port: ${port}`);
      return port;
    } else {
      console.log(`❌ Port ${port} is busy`);
    }
  }
  
  throw new Error(`❌ No available ports found in range ${startPort}-${maxPort}`);
}

// Update frontend configuration with the backend port
function updateFrontendConfig(port) {
  const frontendEnvPath = path.join(__dirname, '../../../frontend/.env.local');
  const envContent = `# Auto-generated by versatile backend
VITE_API_URL=http://localhost:${port}
# Backend running on port ${port}
# Generated at: ${new Date().toISOString()}
# This file is automatically updated when backend starts
`;
  
  try {
    fs.writeFileSync(frontendEnvPath, envContent);
    console.log(`✅ Updated frontend config: VITE_API_URL=http://localhost:${port}`);
    return true;
  } catch (error) {
    console.log(`⚠️  Could not update frontend config: ${error.message}`);
    return false;
  }
}

// Get the best available port (respects environment variable)
async function getBestAvailablePort() {
  // If PORT is set in environment, try to use it first
  if (process.env.PORT) {
    const envPort = parseInt(process.env.PORT);
    const available = await isPortAvailable(envPort);
    if (available) {
      console.log(`✅ Using environment PORT: ${envPort}`);
      return envPort;
    } else {
      console.log(`⚠️  Environment PORT ${envPort} is busy, finding alternative...`);
    }
  }
  
  // Find any available port in preferred ranges
  const portRanges = [
    [5000, 5010], // Primary backend range
    [5010, 5020], // Secondary backend range
    [8000, 8010], // Alternative range
    [3010, 3020]  // High frontend range
  ];
  
  for (const [start, end] of portRanges) {
    try {
      return await findAvailablePort(start, end);
    } catch (error) {
      console.log(`⚠️  No ports available in range ${start}-${end}`);
    }
  }
  
  throw new Error('❌ No available ports found in any range!');
}

module.exports = {
  isPortAvailable,
  findAvailablePort,
  updateFrontendConfig,
  getBestAvailablePort
};