services:
  - type: web
    name: vosk-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: VOSK_MODEL_PATH
        value: ./model
      - key: HUGGINGFACE_MODEL_REPO
        value: Migueldrm/vosk-model-tl-ph-generic-0.6
      - key: PORT
        sync: false  # Render sets this automatically
    plan: starter  # You can change this to free, starter, standard, etc.

