// Versatile Backend Server with Automatic Port Detection
const express = require('express');
const multer = require('multer');
const mongoose = require('mongoose');
const net = require('net');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

// Port detection utility
function isPortAvailable(port) {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.listen(port, () => {
      server.once('close', () => resolve(true));
      server.close();
    });
    server.on('error', () => resolve(false));
  });
}

async function findAvailablePort(startPort = 5000, maxPort = 5020) {
  console.log(`🔍 Scanning for available port (${startPort}-${maxPort})...`);
  
  for (let port = startPort; port <= maxPort; port++) {
    const available = await isPortAvailable(port);
    if (available) {
      console.log(`✅ Found available port: ${port}`);
      return port;
    } else {
      console.log(`❌ Port ${port} is busy`);
    }
  }
  
  throw new Error(`No available ports found in range ${startPort}-${maxPort}`);
}

// Update frontend configuration
function updateFrontendConfig(port) {
  const frontendEnvPath = path.join(__dirname, '../../frontend/.env.local');
  const envContent = `# Auto-generated by versatile backend
VITE_API_URL=http://localhost:${port}
# Backend running on port ${port}
# Generated at: ${new Date().toISOString()}
`;
  
  try {
    fs.writeFileSync(frontendEnvPath, envContent);
    console.log(`✅ Updated frontend config: VITE_API_URL=http://localhost:${port}`);
  } catch (error) {
    console.log(`⚠️  Could not update frontend config: ${error.message}`);
  }
}

async function startServer() {
  try {
    // Find available port
    const PORT = process.env.PORT ? parseInt(process.env.PORT) : await findAvailablePort();
    
    // Update frontend configuration
    updateFrontendConfig(PORT);
    
    // Connect to MongoDB
    console.log('🔌 Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ MongoDB connected successfully');

    // Import the Story model
    const Story = require('./dist/models/Story.js').default;

    // Configure multer
    const upload = multer({
      storage: multer.memoryStorage(),
      limits: { fileSize: 10 * 1024 * 1024 },
      fileFilter: (_req, file, cb) => {
        if (file.mimetype === 'application/pdf') {
          cb(null, true);
        } else {
          cb(new Error('Only PDF files are allowed'));
        }
      },
    });

    // Create Express app
    const app = express();
    app.use(express.json());
    app.use(require('cors')());

    // GET all stories
    app.get('/api/stories', async (req, res) => {
      try {
        console.log('🔍 Getting all stories');
        const stories = await Story.find({ isActive: true }).sort({ createdAt: -1 });
        
        const storiesWithPdfInfo = stories.map(story => ({
          ...story.toObject(),
          hasPdf: !!(story.pdfData || story.pdfFileId)
        }));
        
        console.log(`✅ Found ${stories.length} stories`);
        res.json(storiesWithPdfInfo);
      } catch (error) {
        console.error('❌ Error fetching stories:', error);
        res.status(500).json({ error: 'Failed to fetch stories' });
      }
    });

    // POST create story
    app.post('/api/stories', upload.single('pdf'), async (req, res) => {
      try {
        console.log('📝 Creating new story');
        const { title, description, language, grade, storySet } = req.body;
        
        const storyData = {
          title: title?.trim(),
          description: description?.trim(),
          language: language || 'english',
          grade: grade || 'Grade 1',
          storySet: storySet || 'Set A',
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date()
        };

        if (req.file) {
          storyData.pdfData = req.file.buffer.toString('base64');
        }

        const story = new Story(storyData);
        await story.save();
        
        console.log('✅ Story created successfully:', {
          id: story._id,
          title: story.title,
          grade: story.grade,
          storySet: story.storySet
        });

        res.status(201).json(story);
      } catch (error) {
        console.error('❌ Error creating story:', error);
        res.status(500).json({ error: 'Failed to create story' });
      }
    });

    // PUT update story
    app.put('/api/stories/:id', upload.single('pdf'), async (req, res) => {
      try {
        console.log('📝 Updating story:', req.params.id);
        const story = await Story.findById(req.params.id);
        if (!story) {
          return res.status(404).json({ error: 'Story not found' });
        }

        const updateData = {};
        if (req.body.title) updateData.title = req.body.title.trim();
        if (req.body.description) updateData.description = req.body.description.trim();
        if (req.body.language) updateData.language = req.body.language;
        if (req.body.grade) updateData.grade = req.body.grade;
        if (req.body.storySet) updateData.storySet = req.body.storySet;

        if (req.file) {
          updateData.pdfData = req.file.buffer.toString('base64');
        }

        const updatedStory = await Story.findByIdAndUpdate(req.params.id, updateData, { new: true });
        
        console.log('✅ Story updated successfully:', {
          id: updatedStory._id,
          title: updatedStory.title,
          grade: updatedStory.grade,
          storySet: updatedStory.storySet
        });

        res.json(updatedStory);
      } catch (error) {
        console.error('❌ Error updating story:', error);
        res.status(500).json({ error: 'Failed to update story' });
      }
    });

    // DELETE story
    app.delete('/api/stories/:id', async (req, res) => {
      try {
        console.log('🗑️ Deleting story:', req.params.id);
        const story = await Story.findByIdAndDelete(req.params.id);
        if (!story) {
          return res.status(404).json({ error: 'Story not found' });
        }
        console.log('✅ Story deleted successfully');
        res.json({ message: 'Story deleted successfully' });
      } catch (error) {
        console.error('❌ Error deleting story:', error);
        res.status(500).json({ error: 'Failed to delete story' });
      }
    });

    // GET story PDF
    app.get('/api/stories/:id/pdf', async (req, res) => {
      try {
        const story = await Story.findById(req.params.id);
        if (!story || !story.pdfData) {
          return res.status(404).json({ error: 'PDF not found' });
        }

        const pdfBuffer = Buffer.from(story.pdfData, 'base64');
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `inline; filename="${story.title}.pdf"`);
        res.send(pdfBuffer);
      } catch (error) {
        console.error('❌ Error serving PDF:', error);
        res.status(500).json({ error: 'Failed to serve PDF' });
      }
    });

    // Test PDF upload endpoint
    app.post('/api/test-pdf', upload.single('pdf'), (req, res) => {
      if (!req.file) {
        return res.status(400).json({ error: 'No PDF file uploaded' });
      }
      res.json({ 
        message: 'PDF upload test successful',
        filename: req.file.originalname,
        size: req.file.size,
        mimetype: req.file.mimetype
      });
    });

    // Profile image endpoints (to prevent 404 errors)
    app.get('/api/teachers/:teacherId/profile-image', (req, res) => {
      res.json({ profileImage: null });
    });

    app.post('/api/teachers/:teacherId/profile-image', upload.single('image'), (req, res) => {
      res.json({ message: 'Profile image upload endpoint (not implemented)' });
    });

    app.get('/api/parents/:parentId/profile-image', (req, res) => {
      res.json({ profileImage: null });
    });

    app.post('/api/parents/:parentId/profile-image', upload.single('image'), (req, res) => {
      res.json({ message: 'Profile image upload endpoint (not implemented)' });
    });

    // Teacher sync endpoint
    app.post('/api/teachers/sync', (req, res) => {
      res.json({ message: 'Teacher sync endpoint (not implemented)', success: true });
    });

    // Results endpoints
    app.post('/api/results', (req, res) => {
      res.json({ message: 'Results creation endpoint (not implemented)', _id: 'temp-id-' + Date.now() });
    });

    app.get('/api/results/teacher/:teacherId', (req, res) => {
      res.json([]);
    });

    app.get('/api/results/combined/:studentId', (req, res) => {
      res.json([]);
    });

    app.get('/api/results/student/:studentId', (req, res) => {
      res.json([]);
    });

    // Audio transcription endpoint
    app.post('/api/transcribe', upload.single('audio'), (req, res) => {
      res.json({ message: 'Audio transcription endpoint (not implemented)', transcript: '' });
    });

    // Start the server
    const server = app.listen(PORT, () => {
      console.log('\n🎉 VERSATILE BACKEND SERVER STARTED SUCCESSFULLY!');
      console.log('================================================');
      console.log(`🚀 Server running on port: ${PORT}`);
      console.log(`📡 API base URL: http://localhost:${PORT}/api`);
      console.log(`🌐 Full API URL: http://localhost:${PORT}`);
      console.log('📄 PDF upload validation: ✅ Enabled');
      console.log(`🧪 Test PDF upload: POST http://localhost:${PORT}/api/test-pdf`);
      console.log(`🔧 Frontend config: VITE_API_URL=http://localhost:${PORT}`);
      console.log('================================================\n');
    });

    // Graceful shutdown
    process.on('SIGINT', () => {
      console.log('\n🛑 Shutting down server gracefully...');
      server.close(() => {
        console.log('✅ Server closed');
        mongoose.connection.close(() => {
          console.log('✅ MongoDB connection closed');
          process.exit(0);
        });
      });
    });

    return { app, server, port: PORT };

  } catch (error) {
    console.error('❌ Failed to start server:', error);
    process.exit(1);
  }
}

// Start the server
if (require.main === module) {
  startServer();
}

module.exports = { startServer, findAvailablePort, updateFrontendConfig };